/* V10.5 GAME-original guardian micro-quests keyed to owner's appendix disciplines;
 * NOT quotations or a claim that this alone fully adapts all 47 novel pages.
 * Each unlocked guardian has a separate replayable atlas FIELD map and two
 * geographically disjoint, player-operated quest stations. No auto-complete. */
#ifndef LC_G5_DATA_H
#define LC_G5_DATA_H
#define G5_SRAM 4096
#define G5_BYTES 32
#define G5_NONE 17
#define TR_G5_OATH 57
#define TR_G5_PROOF 58
#define TR_G5_BOOK_OAK 59
#define TR_G5_BOOK_TEMPLE 60
#define TR_G5_BOOK_HOME 61
static u32 g5_complete=0;
static u8 g5_active=G5_NONE,g5_journal_sel=0;
static u16 g5_start_kills=0;
static u8 g5_book_step=0; /* Actual optional 3-site Chapter I route, 0..3. */
static const char*const G5_NAME[17]={
 "THE FORGE OATH","THE WINDMARK","THE RUNEWEAVE","THE HEALERS PACT",
 "THE IRON SHIELD","THE ELEMENT CIRCUIT","THE SHADOW CACHE",
 "THE ROOT TREATY","THE BROKEN HOUR","THE LIVING THREAD",
 "THE STAR EMBER","THE VEIL VOW","THE FESTIVAL SONG",
 "THE SPIRIT BOND","THE COPPER RELAY","THE WORLDS ANVIL",
 "THE KEEPERS RECORD"};
static const char*const G5_HINT[17]={
 "WIN TWO REAL BATTLES AFTER TAKING ARINS OATH.",
 "CLAIM ELIRAS ROOM CACHE AND EARN ONE SKY ASH.",
 "HOLD THREE MANA AND EARN ONE TIDE GLASS.",
 "BRING ONE ROOTLEAF AND ONE FIELD POTION.",
 "SURVIVE THREE REAL BATTLES AFTER THE SHIELD OATH.",
 "EARN ONE EMBER ORE AND ONE TIDE GLASS.",
 "FIND ANARAS ROOM CACHE AND ONE VOID DUST.",
 "FINISH THREE PETALS AND GATHER ONE ROOTLEAF.",
 "STABILIZE BOTH ANCHORS; BRING ONE TIDE GLASS.",
 "RAISE AN ACTIVE CREATURES TRUST TO SEVENTY.",
 "BRING ONE SKY ASH AND ONE RESTORING ETHER.",
 "WIN ONE BATTLE AND EARN ONE VOID DUST.",
 "RESTORE THE DREAM FESTIVAL; BRING ONE SKY ASH.",
 "BOND A ROOTKIN AT TRUST FIFTY FIVE; BRING ROOTLEAF.",
 "RESTORE ALL THREE AXES; BRING ORE AND VOID DUST.",
 "DELIVER ONE OF EACH FIVE BIOME MATERIALS.",
 "AFTER ENDING, FIND FOUR CACHES AND BRING THREE SHARDS."};
static const char*const G5_OATH[17]={
 "ARIN: HOLD THE FORGE LINE. SHOW ME TWO REAL VICTORIES.",
 "ELIRA: FOLLOW THE WIND. RECLAIM THIS ROOMS HIDDEN CACHE.",
 "THALIAN: WEAVE THE TIDE THROUGH YOUR OWN MAGIC.",
 "LYRA: HEAL THE LAND WITH MATERIALS YOU EARNED.",
 "DARIUS: A SHIELD IS FOR OTHERS. WIN THREE FIGHTS.",
 "SORIN: JOIN FIRE WITH WATER WITHOUT ERASING EITHER.",
 "ANARA: FIND THE CACHE AND LEARN THE VOIDS PATH.",
 "ELYSIA: THE PETALS AND THE ROOTS MUST AGREE.",
 "KAELEN: SET BOTH HOURS RIGHT. BRING THE TIDES RECORD.",
 "SERAPHINA: TRUST A CREATURE BEFORE ASKING FOR POWER.",
 "MARISOL: JOIN A STAR ASH TO THE GIFT OF RESTORATION.",
 "RIVEN: RETURN FROM THE VEIL WITH A REAL VICTORY.",
 "NYSSA: LET THE FESTIVAL FINISH BEFORE THE LAST VERSE.",
 "ZEPHRA: THE ROOTKIN MUST CHOOSE TO TRUST YOU FIRST.",
 "THORNE: USE ALL THREE AXES TO REPAIR THE COPPER RELAY.",
 "MAIA: CRAFT WITH EVERYTHING EACH WORLD TAUGHT YOU.",
 "ALTAIR: CARRY THE RECORDS AND YOUR ENDING INTO HISTORY."};
static const char*const G5_DONE[17]={
 "ARIN: THIS OATH REMAINS YOURS.","ELIRA: THE WINDMARK WILL GUIDE YOUR ARROWS.",
 "THALIAN: YOU HAVE LEARNED TO READ THE TIDE.","LYRA: YOU HEALED WITHOUT TAKING THE GROVES LAST GIFT.",
 "DARIUS: YOUR SHIELD NOW STANDS BETWEEN TWO WORLDS.",
 "SORIN: THE TWO ELEMENTS ANSWER TO ONE PURPOSE.",
 "ANARA: YOU LEARNED THE HIDDEN ROAD BY WALKING IT.",
 "ELYSIA: THE ROOTS REMEMBER YOUR PROMISE.",
 "KAELEN: YOU HELD BOTH HOURS WITHOUT ERASING EITHER.",
 "SERAPHINA: A FRIEND CHOSE TO STAY. THAT IS ENOUGH.",
 "MARISOL: THE SHARED STAR BURNS BRIGHTER.",
 "RIVEN: YOU RETURNED FROM THE DARK WITH YOURSELF INTACT.",
 "NYSSA: EVERY VOICE HAS A PLACE IN THE SONG.",
 "ZEPHRA: THE SPIRITS GAVE THEIR CONSENT.",
 "THORNE: THE RELAY REMEMBERS ITS BUILDER.",
 "MAIA: EVERY WORLD LEFT ITS MARK UPON YOUR WORK.",
 "ALTAIR: THE RECORD WILL BE KEPT WITHOUT ERASING A PATH."};
/* Upgrades apply ONLY when the corresponding story ally is equipped and their
 * own two-site personal quest has actually been finished. */
static const u8 G5_ATK[17]={2,2,1,0,0,2,2,0,0,0,1,2,0,1,1,1,0};
static const u8 G5_DEF[17]={0,0,1,2,2,0,0,2,1,2,1,0,2,1,1,1,2};
static int g5_bonus_attack(u8 idx){return idx<17&&(g5_complete&(1u<<idx))?G5_ATK[idx]:0;}
static int g5_bonus_guard(u8 idx){return idx<17&&(g5_complete&(1u<<idx))?G5_DEF[idx]:0;}
static void g5_reset(void){g5_complete=0;g5_active=G5_NONE;g5_start_kills=0;g5_journal_sel=0;g5_book_step=0;}
#endif
