/* V10.7 NATIVE source-informed optional story rooms, not raw private book.
 * Existing V10...V10.6 atlas, original 8 worlds and all 6 saved pages survive.
 * The literary elder is NOT game appendix Technomancer Thorne;
 * unnamed literary Dreamweaver is NOT silently identified as Nyssa.
 * Celestial Harmony AND Ember Passion remain two distinct crystal pickups. */
#ifndef LC_G7_DATA_H
#define LC_G7_DATA_H
#define G7_FIRST_ROOM 34
#define G7_COUNT 12
#define G7_SRAM 6144
#define G7_SRAM_BYTES 64
#define G7_IS_ROOM (current_world==0 && current_room>=G7_FIRST_ROOM && current_room<G7_FIRST_ROOM+G7_COUNT)
#define TR_G7_PORTAL 71
#define TR_G7_OATH 72
#define TR_G7_CHOICE 73
#define TR_G7_NODE_A 74
#define TR_G7_NODE_B 75
#define TR_G7_PROOF 76
#define TR_G7_CACHE 77
#define TR_G7_EXIT 78
#define TR_G7_NEXT 79
#define TR_G7_SIGIL_FIRST 80
#define TR_G7_SIGIL_LAST 83
#define TR_G7_PILLAR 84
#define TR_G7_ORB_FIRST 85
#define TR_G7_ORB_LAST 89
static u16 g7_done=0,g7_cache=0;
static u8 g7_step[G7_COUNT]={0},g7_choice[G7_COUNT]={0},g7_nodes[G7_COUNT]={0};
static u8 g7_pending=0,g7_journal_sel=0,g7_sigils=0,g7_orbs=0,g7_pillars=0;
static u16 g7_pillar_kills=0;
static const u8 G7_PARENT[G7_COUNT]={10,10,11,11,12,12,12,13,13,14,15,15};
static const u8 G7_FLOOR[G7_COUNT]={T_GRASS,T_GRASS,T_RUIN,T_ARCHIVE,T_WATER,T_RUIN,T_GRASS,T_FLOWER,T_MOON,T_VOID,T_RUIN,T_ARCHIVE};
static const u8 G7_DECOR[G7_COUNT]={T_TREE,T_VINES,T_PILLAR,T_PILLAR,T_TREE,T_CRYSTAL,T_VINES,T_LANTERN,T_FLOWER,T_CRYSTAL,T_PILLAR,T_CIRCUIT};
static const u8 G7_ACCENT[G7_COUNT]={T_FLOWER,T_LANTERN,T_CRYSTAL,T_RUNE,T_MOON,T_FLOWER,T_PLANT,T_MOON,T_STAR,T_CIRCUIT,T_STAR,T_CROWN};
static const char*const G7_NAMES[G7_COUNT]={"ELDORIA CALL",
"LANTERN WOODS",
"THE WRAITH ALTAR",
"FOUR LIVING WINDS",
"STILL WATER POOL",
"THE EARTH PROMISE",
"THE FOREST BREATHES",
"SHARING OF TALES",
"LAST DREAM SONG",
"VALTARA SIGILS",
"TWILIGHT PILLARS",
"THE FIVE ORBS"};
static const char*const G7_ACT[G7_COUNT]={"IV","IV","IV","IV","IV","IV","IV","IV","IV","III","IV","V"};
static const char*const G7_OATH[G7_COUNT]={"ELDER THORNE SENDS YOU TO FIND THE OLD RUINS.",
"TAKE THE LANTERN PAST THE WHISPERING TREES.",
"AN OLD ALTAR STIRS BENEATH THE BROKEN STATUES.",
"A GUARDIAN MAP MARKS EARTH WATER FIRE AND AIR.",
"THE FOREST HIDES ITS PATH IN A STILL REFLECTION.",
"A CAVERN SPIRIT ASKS WHAT YOU CAN ALWAYS KEEP.",
"THE BLIGHTED GUARDIAN IS HURT NOT LOST.",
"THE FESTIVAL ASKS FOR A STORY NOT A VICTORY.",
"A GLOWING ORB MARKS A NIGHT OF PARTING STARS.",
"FOUR DISTINCT SIGILS STABILIZE THE VOIDWARD.",
"THREE PILLARS RESTORE THE PATH PAST THE CITADEL.",
"THE LATTICE NEEDS FIVE PROVEN ROOTED POWERS."};
static const char*const G7_CHOICES[G7_COUNT]={"ELDER: LEFT HELP UP PREPARE RIGHT ASK",
"LANTERN: LEFT SCOUT UP LISTEN RIGHT GUIDE",
"WRAITH: LEFT HEAL UP DEFEND RIGHT STUDY",
"MAP: LEFT EXPLORE UP PROTECT RIGHT RECORD",
"POOL: LEFT WAIT UP OBSERVE RIGHT TRUST",
"SPIRIT: LEFT PROMISE UP REFUSE RIGHT LEARN",
"ROOTS: LEFT MEND UP GUARD RIGHT REPLANT",
"TALES: LEFT SHARE UP LISTEN RIGHT SING",
"DREAM: LEFT THANK UP DANCE RIGHT REMEMBER",
"VOID: LEFT GUARD UP REBUILD RIGHT INVESTIGATE",
"PILLARS: LEFT STAND UP COOPERATE RIGHT CHALLENGE",
"ORBS: LEFT OPEN UP PRESERVE RIGHT WANDER"};
static const char*const G7_NODE_LINE[G7_COUNT]={"THE ELDER SHARES THE FORGOTTEN WOODLAND ROAD.",
"REFLECTIONS IN THE WATER POINT TO A SAFE PASS.",
"MERCY AND A TRUE EARTH MEMORY DISARM THE CURSE.",
"FOUR SHRINES BECOME ONE REAL PATH THROUGH ELDORIA.",
"THE WATER SHOWS THE HOLLOW GROVE BELOW THE TREES.",
"A PROMISE JOINS THE GROUND TO THOSE WHO CARE.",
"A REAL ROOTLEAF LETS THE GARDEN GROW AGAIN.",
"THE UNNAMED DREAMWEAVER PLAYS FOR THE FAIRIES.",
"THE FAIRY RETAINS THE MEMORY OF YOUR VISIT.",
"VALTARA AND THE LOST ARCHIVES HOLD THE FOUR SEALS.",
"AN EARNED VICTORY OPENS EACH NEW PILLAR.",
"THE ORIGINAL PLAYER ENDING REMAINS UNCHANGED."};
static const char*const G7_HINT[G7_COUNT]={"SUPPLIES AND TWO SEPARATE CRYSTALS OPEN THE ROUTE.",
"RETURN WITH THE LANTERN AND AN OLD MEMORY.",
"THE WRAITH MUST BE SETTLED BEFORE THE ALTAR.",
"EARN THE FOUR ORIGINAL ELEMENTAL SHRINES.",
"SOLVE THE ORIGINAL REFLECTION RIDDLE.",
"CLAIM THE ACTUAL EARTH CRYSTAL.",
"EARN EARTH AND ONE GENUINE ROOTLEAF.",
"COMPLETE THE ORIGINAL DREAM FESTIVAL.",
"SHARE ONE FESTIVAL MEMORY BEFORE DEPARTURE.",
"RECOVER THE ORIGINAL VOIDWARD AND CHRONOHEART.",
"RESTORE THE ORIGINAL LATTICE FIRST.",
"REACH A REAL ENDING AND RESTORE ALL FIVE ORBS."};
static void g7_reset(void){int i;g7_done=g7_cache=0;g7_pending=g7_journal_sel=0;
 g7_sigils=g7_orbs=g7_pillars=0;g7_pillar_kills=0;
 for(i=0;i<G7_COUNT;i++){g7_step[i]=0;g7_choice[i]=0;g7_nodes[i]=0;}}
static int g7_attack_bonus(void){int n=0,i;for(i=0;i<G7_COUNT;i++)
 if((g7_done&(1u<<i))&&g7_choice[i]==2)n++;return mini(n,4);}
static int g7_guard_bonus(void){int n=0,i;for(i=0;i<G7_COUNT;i++)
 if((g7_done&(1u<<i))&&g7_choice[i]==1)n++;return mini(n,4);}
#endif
