#include "cosmos/cst_state.hpp"
#include "cosmos/live_data.hpp"
#include "cosmos/persistence.hpp"
#include "cosmos/renderer.hpp"
#include "cosmos/universe.hpp"
#include "raylib.h"
#include <chrono>
#include <string>
using namespace cosmos;static double unixMs(){return(double)std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
int main(){SetConfigFlags(FLAG_WINDOW_RESIZABLE|FLAG_VSYNC_HINT|FLAG_MSAA_4X_HINT);InitWindow(1440,900,"Cosmic Synapse // Living Universe");SetTargetFPS(120);Simulation sim;sim.planet=makePlanet("Earth");sim.clock.simUnixMs=unixMs();resetPlayerToSpawn(sim);loadWorld("runtime/worlds",sim);CSTStateEngine stateEngine;Renderer renderer(GetScreenWidth(),GetScreenHeight());double accumulator=0,fixed=1.0/60.0,livePoll=0,saveTimer=0;bool quakeLatched=false;while(!WindowShouldClose()){double frame=std::min(.1,(double)GetFrameTime());accumulator+=frame;livePoll+=frame;saveTimer+=frame;if(livePoll>5){loadLiveDataTSV("runtime/live_data.tsv",sim.live);livePoll=0;}if(IsKeyPressed(KEY_TAB))renderer.setMode(renderer.mode()+1);if(IsKeyPressed(KEY_T))sim.clock.timeWarp=sim.clock.timeWarp==1?10:sim.clock.timeWarp==10?100:1;if(IsKeyPressed(KEY_L)){seedLife(sim);appendLedger("runtime/ledger.jsonl","LIFE","Life seeded",sim);}if(IsKeyPressed(KEY_O)){addOutpost(sim);appendLedger("runtime/ledger.jsonl","OUTPOST","Outpost anchored",sim);}if(IsKeyPressed(KEY_K)){injectStorm(sim);appendLedger("runtime/ledger.jsonl","WEATHER","Storm injected",sim);}if(IsKeyPressed(KEY_X)){manifestAnomaly(sim);appendLedger("runtime/ledger.jsonl","ANOMALY","Anomaly manifested",sim);}if(IsKeyPressed(KEY_F)){saveWorld("runtime/worlds",sim);std::string next=sim.planet.name=="Earth"?"Mars":sim.planet.name=="Mars"?"Europa":sim.planet.name=="Europa"?"Cory Prime":"Earth";foldTo(sim,next);loadWorld("runtime/worlds",sim);appendLedger("runtime/ledger.jsonl","FOLD","Folded to "+next,sim);renderer.setMode(0);}double forward=(IsKeyDown(KEY_W)||IsKeyDown(KEY_UP)?1:0)-(IsKeyDown(KEY_S)||IsKeyDown(KEY_DOWN)?1:0),strafe=(IsKeyDown(KEY_D)?1:0)-(IsKeyDown(KEY_A)?1:0);sim.player.heading+=(IsKeyDown(KEY_RIGHT)?1:0)*frame*1.2-(IsKeyDown(KEY_LEFT)?1:0)*frame*1.2;bool jump=IsKeyPressed(KEY_SPACE);while(accumulator>=fixed){updatePlayer(sim,fixed,forward,strafe,jump,IsKeyDown(KEY_LEFT_SHIFT)||IsKeyDown(KEY_RIGHT_SHIFT));jump=false;updateWorld(sim,fixed);sim.sensors.visionLuminance=std::max(.05,std::min(1.0,sim.sensors.visionLuminance+(sim.live.solarFlareCount?0.0002:-0.00005)));if(sim.live.latestQuakeMagnitude>6&&!quakeLatched){sim.world.anomalies++;appendLedger("runtime/ledger.jsonl","LIVE_REACTION","Major quake feed mapped to simulated anomaly",sim);quakeLatched=true;}if(sim.live.latestQuakeMagnitude<=6)quakeLatched=false;sim.state=stateEngine.update(fixed,sim);accumulator-=fixed;}if(saveTimer>5){saveWorld("runtime/worlds",sim);saveTimer=0;}BeginDrawing();renderer.render(sim,GetTime());EndDrawing();}saveWorld("runtime/worlds",sim);CloseWindow();}
