#include "cosmos/renderer.hpp"
#include "cosmos/math.hpp"
#include "cosmos/universe.hpp"
#include "raylib.h"
#include <algorithm>
#include <cmath>
namespace cosmos{
static Color hsl(double h,double s,double l,unsigned char a=255){h=fract(h/360.0);s=clamp(s/100.0);l=clamp(l/100.0);double r,g,b;if(s==0)r=g=b=l;else{auto hue=[](double p,double q,double t){if(t<0)t+=1;if(t>1)t-=1;if(t<1.0/6)return p+(q-p)*6*t;if(t<.5)return q;if(t<2.0/3)return p+(q-p)*(2.0/3-t)*6;return p;};double q=l<.5?l*(1+s):l+s-l*s,p=2*l-q;r=hue(p,q,h+1.0/3);g=hue(p,q,h);b=hue(p,q,h-1.0/3);}return{(unsigned char)(r*255),(unsigned char)(g*255),(unsigned char)(b*255),a};}
Renderer::Renderer(int,int){}Renderer::~Renderer(){if(apodId_){Texture2D t{apodId_,apodW_,apodH_,1,PIXELFORMAT_UNCOMPRESSED_R8G8B8A8};UnloadTexture(t);}}void Renderer::setMode(int m){mode_=((m%3)+3)%3;}void Renderer::refreshApodTexture(const LiveData&live){if(live.apodLocalPath.empty()||live.apodLocalPath==loadedApod_||!FileExists(live.apodLocalPath.c_str()))return;if(apodId_){Texture2D old{apodId_,apodW_,apodH_,1,PIXELFORMAT_UNCOMPRESSED_R8G8B8A8};UnloadTexture(old);}Texture2D t=LoadTexture(live.apodLocalPath.c_str());if(t.id){apodId_=t.id;apodW_=t.width;apodH_=t.height;loadedApod_=live.apodLocalPath;}}
void Renderer::drawOrbit(const Simulation&sim,double t){ClearBackground(BLACK);int w=GetScreenWidth(),h=GetScreenHeight();std::uint64_t s=0x707C05A05ull;for(int i=0;i<700;i++){double x=rand01(s)*w,y=rand01(s)*h,tw=.4+.6*std::sin(t*(.5+rand01(s))+rand01(s)*6.28);DrawPixel((int)x,(int)y,Color{180,230,255,(unsigned char)(80+std::max(0.0,tw)*175)});}Vector2 c{w*.52f,h*.48f};float r=(float)std::min(w,h)*.20f;Color base=hsl(sim.planet.hue,sim.planet.saturation,sim.planet.lightness);for(int k=12;k>=0;k--)DrawCircleV(c,r*(1+k*.07f),Fade(base,.03f+(12-k)*.015f));DrawCircleGradient((int)c.x,(int)c.y,r,ColorBrightness(base,.45f),ColorBrightness(base,-.45f));if(sim.planet.rings)for(int i=0;i<10;i++)DrawEllipseLines((int)c.x,(int)c.y,(float)(r*(1.25+i*.04)),(float)(r*.23*(1+i*.01)),Fade(RAYWHITE,.35f));DrawText(TextFormat("%s // ORBIT",sim.planet.name.c_str()),(int)(c.x-r),(int)(c.y+r+28),20,RAYWHITE);if(sim.live.solarFlareCount>0)DrawCircleLines((int)c.x,(int)c.y,r*1.55f,Fade(ORANGE,(float)(.3+.25*std::sin(t*6))));int neo=std::min(80,sim.live.neoCount);std::uint64_t ns=sim.planet.seed^0x4E454Full;for(int i=0;i<neo;i++){float a=(float)(rand01(ns)*2*PI),rr=r*(1.8f+(float)rand01(ns)*1.2f);DrawCircle((int)(c.x+std::cos(a)*rr),(int)(c.y+std::sin(a)*rr),1.5f,GOLD);}}
void Renderer::drawSurface(const Simulation&sim,double t){int w=GetScreenWidth(),h=GetScreenHeight();double day=clamp((std::sin(sim.clock.localDay*PI*2)+.15)/.5);DrawRectangleGradientV(0,0,w,h,hsl(225*(1-day)+sim.planet.hue*day,50,4+day*40),hsl(sim.planet.hue+20,45,8+day*38));if(day<.5){std::uint64_t s=sim.planet.seed^42;for(int i=0;i<280;i++)DrawPixel((int)(rand01(s)*w),(int)(rand01(s)*h*.55),Fade(RAYWHITE,(float)(.2+rand01(s)*(1-day))));}int horizon=(int)(h*.47+sim.player.pitch*90);double focal=w*.86;int step=w<900?4:3;for(int sx=0;sx<w;sx+=step){double ang=sim.player.heading+(double(sx)/w-.5)*1.05,ca=std::cos(ang),sa=std::sin(ang);int maxY=h;for(double z=1;z<280&&maxY>horizon;z+=std::max(.8,z*.03)){double wx=sim.player.x+ca*z,wz=sim.player.z+sa*z,hh=terrainHeight(sim.planet,wx,wz);if(sim.planet.water>.2&&hh<-1.2)hh=-1.2;int sy=(int)(horizon-(hh-sim.player.y)*focal/z);if(sy<maxY){double fog=clamp(z/260.0);DrawRectangle(sx,sy,step+1,maxY-sy,hsl(sim.planet.hue+(hh>0?25:0),sim.planet.saturation*(1-fog*.6),clamp(sim.planet.lightness+hh*.3,8.0,72.0)));maxY=sy;}}}for(auto&o:sim.world.outposts){double dx=o.x-sim.player.x,dz=o.z-sim.player.z,dist=std::hypot(dx,dz);if(dist>180||dist<2)continue;double a=normAngle(std::atan2(dz,dx)-sim.player.heading);if(std::abs(a)>.72)continue;float sx=(float)(w*.5+std::tan(a)*focal),scale=(float)clamp(focal/dist,4.0,100.0);DrawTriangle({sx,horizon-scale*.9f},{sx-scale*.35f,(float)horizon},{sx+scale*.35f,(float)horizon},Fade(SKYBLUE,.65f));}if(sim.world.storm>.01)DrawRectangle(0,0,w,h,Fade(Color{20,25,36,255},(float)(sim.world.storm*.45)));DrawLine(w/2-8,h/2,w/2+8,h/2,Fade(RAYWHITE,.6f));DrawLine(w/2,h/2-8,w/2,h/2+8,Fade(RAYWHITE,.6f));(void)t;}
void Renderer::drawApod(const Simulation&sim,double){ClearBackground(BLACK);int w=GetScreenWidth(),h=GetScreenHeight();if(apodId_){Texture2D t{apodId_,apodW_,apodH_,1,PIXELFORMAT_UNCOMPRESSED_R8G8B8A8};float scale=std::max((float)w/t.width,(float)h/t.height);Rectangle src{0,0,(float)t.width,(float)t.height},dst{(w-t.width*scale)/2.0f,(h-t.height*scale)/2.0f,t.width*scale,t.height*scale};DrawTexturePro(t,src,dst,{0,0},0,WHITE);DrawRectangle(0,h-150,w,150,Fade(BLACK,.72f));}else DrawText("APOD IMAGE NOT CACHED YET",40,80,24,SKYBLUE);DrawText(sim.live.apodTitle.c_str(),30,h-118,24,RAYWHITE);DrawText(sim.live.stale?"LIVE BRIDGE: STALE/OFFLINE":"LIVE BRIDGE: FRESH",30,h-50,16,sim.live.stale?ORANGE:LIME);}
void Renderer::drawHud(const Simulation&sim){DrawRectangle(12,12,540,108,Fade(BLACK,.55f));DrawText(TextFormat("COSMIC SYNAPSE // %s",sim.planet.name.c_str()),24,22,20,SKYBLUE);DrawText(TextFormat("g %.3f | temp %.0f C | bio %.3f | anomaly %d | warp x%.0f",sim.planet.gravityG,sim.planet.temperatureC,sim.world.biosphere,sim.world.anomalies,sim.clock.timeWarp),24,50,16,RAYWHITE);DrawText(TextFormat("54D coherence %.3f | chaos %.3f | resonance %.3f",sim.state.d54[41],sim.state.d54[15],sim.state.d54[52]),24,74,16,LIGHTGRAY);DrawText(TextFormat("APOD %s | NEO %d | flare %d | quake %.1f",sim.live.apodTitle.c_str(),sim.live.neoCount,sim.live.solarFlareCount,sim.live.latestQuakeMagnitude),24,96,14,LIGHTGRAY);DrawText("TAB mode | WASD move | SPACE jump | F fold | L life | O outpost | K storm | X anomaly | T warp",12,GetScreenHeight()-26,14,Fade(RAYWHITE,.75f));}
void Renderer::render(const Simulation&sim,double t){refreshApodTexture(sim.live);if(mode_==0)drawOrbit(sim,t);else if(mode_==1)drawSurface(sim,t);else drawApod(sim,t);drawHud(sim);}
}
