#!/usr/bin/env python3
"""Actual native C import/evolution/save rules using simulated GBA MMIO.
Separate from genuine controller-only mGBA acceptance, never claimed as play.
"""
from pathlib import Path
import json,os,subprocess,tempfile
ROOT=Path(__file__).resolve().parents[1];GAME=ROOT/'LOST_COSMOS_V10_SOURCE';REPO=ROOT.parents[1]
js="""
import fs from 'node:fs';
import {createBeast,exportSave} from './arcade/sol-beast-lab/design.mjs';
import {renderSprite,packTiles} from './arcade/sol-beast-lab/sprites.mjs';
const a=new Uint8Array(JSON.parse(fs.readFileSync('arcade/sol-beast-lab/archive.json')).bytes);
const b=createBeast({island:0,nonce:'CORY-SOL-001',focus:65,calm:72,spark:48},a);
console.log(JSON.stringify({id:b.publicId,seed:b.gameSeed,bond:b.bond,mail:[...exportSave(b).slice(24832,25476)],stages:[0,1,2].map(s=>[...packTiles(renderSprite(b,s).pixels)])}));
"""
fixture=json.loads(subprocess.check_output(['node','--input-type=module','-e',js],cwd=REPO,text=True))
subprocess.run(['python3','host_qa_v5.py'],cwd=GAME,check=True,capture_output=True)
pre=(GAME/'host_qa_v5.c').read_text().split('\n#ifdef HOST_QA\nint main(',1)[0]
arrays='static const u8 mail[644]={'+','.join(map(str,fixture['mail']))+'};\n'
for i,data in enumerate(fixture['stages']):arrays+=f'static const u8 stage{i}[512]={{'+','.join(map(str,data))+'};\n'
body=r'''
#include <assert.h>
#include <stdio.h>
static void unchanged_art(const u8 *expected){
 u8 save[32768];for(int i=0;i<32768;i++)save[i]=SRAM[i];
 lc_mail_blit();
 for(int i=0;i<512;i++)assert(lc_mail_tiles[i]==expected[i]);
 for(int i=0;i<32768;i++)assert(save[i]==SRAM[i]);
}
int main(void){
 for(int i=0;i<32768;i++)SRAM[i]=255;
 for(int i=0;i<644;i++)SRAM[24832+i]=mail[i];
 init_graphics();init_new_game();intro=v10_opening=cinema_active=0;save_game();
 assert(lc_mail_ready&&lc_mail_live);
 int ix=-1;for(int i=0;i<lc_party.count;i++)if(lc_party.slots[i].identity==SOL_ID)ix=i;
 assert(ix>=0);LcCreature*c=&lc_party.slots[ix];
 assert(c->seed==SOL_SEED&&c->stage==0&&c->level==1&&c->bond==SOL_BOND);
 unchanged_art(stage0);assert(lc_evolve(&lc_party,ix,1)==LC_NOT_READY);
 while(c->level<28)assert(lc_reward_xp(&lc_party,ix,65535)==LC_OK);
 while(c->bond<80)assert(lc_bond(&lc_party,ix,(c->species-128)%3,85)==LC_OK);
 assert(lc_evolve(&lc_party,ix,1)==LC_OK);assert(c->stage==1);
 unchanged_art(stage1);assert(lc_evolve(&lc_party,ix,1)==LC_OK);assert(c->stage==2);
 unchanged_art(stage2);assert(c->identity==SOL_ID&&c->seed==SOL_SEED);
 save_game();lc_roster_init(&lc_party);load_game();
 assert(lc_party.slots[ix].stage==2&&lc_party.slots[ix].identity==SOL_ID);
 unchanged_art(stage2);
 /* Unrelated custom art cannot be regenerated by the nursery renderer. */
 lc_mail_pal[26]=0;for(int i=0;i<512;i++)lc_mail_tiles[i]=stage0[i];
 unchanged_art(stage0);
 puts("PASS: native nursery import, earned two-stage evolution, read-only art, same-identity save/load, unrelated art preserved");return 0;
}
'''
definitions=f'#define SOL_ID {fixture["id"]}u\n#define SOL_SEED {fixture["seed"]}u\n#define SOL_BOND {fixture["bond"]}\n'
with tempfile.TemporaryDirectory(prefix='sol-nursery-') as temp:
 p=Path(temp);(p/'test.c').write_text(pre+definitions+arrays+body)
 for imported in (False,True):
  cmd=[os.environ.get('LC_HOST_CC','gcc'),'-DQA_AUTORUN','-DHOST_QA','-O2','-I',str(GAME)]
  if imported:cmd.append('-DLC_IMPORTED_COMPANION')
  subprocess.run(cmd+[str(p/'test.c'),'-o',str(p/'test')],check=True)
  subprocess.run([str(p/'test')],check=True)
