  const start=performance.now(),c=this.ctx,p=this.app.planet,pl=this.app.player;if(p.atmo>50&&p.radiusKm>15000){this.drawGasSurface(t);this.lastRenderMs=lerp(this.lastRenderMs,performance.now()-start,.12);return;}this.drawSky(t);const horizon=clamp(this.h*.47+pl.pitch*95,this.h*.21,this.h*.72);const focal=this.w*.86;const mobile=this.w<760;const stepX=mobile?(this.lastRenderMs>22?5:4):(this.lastRenderMs>23?3:2);const far=mobile?265:360;
  for(let sx=0;sx<this.w;sx+=stepX){const ang=pl.heading+(sx/this.w-.5)*1.05;const ca=Math.cos(ang),sa=Math.sin(ang);let maxY=this.h;let z=1;while(z<far&&maxY>horizon){const wx=pl.x+ca*z,wz=pl.z+sa*z;let hh=this.terrain(wx,wz);if(p.water>.18&&hh<-1.2)hh=-1.2;const sy=horizon-(hh-pl.y)*focal/z;if(sy<maxY){c.fillStyle=this.surfaceColor(wx,wz,hh,z,t);c.fillRect(sx,sy,stepX+1,maxY-sy+1);maxY=sy}z+=Math.max(.72,z*.028)}}
  this.drawWaterHighlights(t,horizon);this.drawGroundDetails(t,horizon,focal);this.drawObjects(t,horizon,focal);this.drawAmbientLife(t,horizon);this.drawWeather(t);if(this.app.world.storm>.55&&Math.random()<.025){c.strokeStyle='rgba(218,247,255,.78)';c.lineWidth=1.6;c.beginPath();let x=this.w*(.2+Math.random()*.6),y=0;c.moveTo(x,y);for(let i=0;i<8;i++){x+=(Math.random()-.5)*40;y+=this.h*.075;c.lineTo(x,y)}c.stroke()}this.drawAtmosphereVignette();this.lastRenderMs=lerp(this.lastRenderMs,performance.now()-start,.12)
 }
 drawAmbientLife(t,horizon){
  const c=this.ctx,p=this.app.planet,w=this.app.world,{day}=this.skyInfo();if(w.biosphere<.28||p.atmo<.08)return;const r=seeded(p.seed,'ambient-life');c.save();if(day>.18){const n=Math.floor((4+w.biosphere*9)*this.quality);c.strokeStyle=`rgba(29,45,42,${.22+.28*day})`;c.lineWidth=1.1;for(let i=0;i<n;i++){const x=fract(r()+t*.000018*(.3+p.wind)+i*.071)*this.w,y=this.h*(.14+r()*.27),wing=2+r()*5,flap=Math.sin(t*.009+i*1.8)*wing*.55;c.beginPath();c.moveTo(x-wing,y);c.quadraticCurveTo(x-wing*.35,y-flap,x,y);c.quadraticCurveTo(x+wing*.35,y+flap,x+wing,y);c.stroke()}}if(day<.36&&w.biosphere>.48){const n=Math.floor(22*w.biosphere*this.quality);for(let i=0;i<n;i++){const x=fract(r()+Math.sin(t*.0002+i)*.02)*this.w,y=horizon+fract(r()+t*.000004*(.3+r()))*(this.h-horizon)*.72,tw=.25+.75*(.5+.5*Math.sin(t*.004+i*2.4));c.fillStyle=`rgba(210,255,130,${.08+.36*tw})`;c.beginPath();c.arc(x,y,.5+r()*1.4,0,PI*2);c.fill()}}c.restore()
 }
 drawWaterHighlights(t,horizon){const c=this.ctx,p=this.app.planet;if(p.water<.18)return;const r=seeded(p.seed,'water-glints');c.save();c.globalCompositeOperation='screen';for(let i=0;i<28*this.quality;i++){const y=horizon+fract(r()+t*.000002*(1+i*.02))*Math.max(8,this.h-horizon);const wid=4+r()*36,alpha=.015+r()*.06*this.app.lightFactor;c.strokeStyle=`rgba(180,232,255,${alpha})`;c.beginPath();c.moveTo(r()*this.w,y);c.lineTo(Math.min(this.w,r()*this.w+wid),y);c.stroke()}c.restore()}
 project(x,z,h,horizon,focal){const pl=this.app.player,dx=x-pl.x,dz=z-pl.z,dist=Math.hypot(dx,dz);if(dist<.35)return null;const angle=normAngle(Math.atan2(dz,dx)-pl.heading);if(Math.abs(angle)>.74)return null;return{dist,angle,x:this.w*.5+Math.tan(angle)*focal,y:horizon-(h-pl.y)*focal/dist,scale:clamp(focal/dist,1,150)}}
 drawGroundDetails(t,horizon,focal){
