  const c=this.ctx,p=this.app.planet,pl=this.app.player,w=this.app.world;const cell=3.6,range=7,cx=Math.floor(pl.x/cell),cz=Math.floor(pl.z/cell),items=[];for(let gx=cx-range;gx<=cx+range;gx++)for(let gz=cz-range;gz<=cz+range;gz++){const rr=seeded(p.seed,`micro:${gx}:${gz}`);if(rr()>.52+Math.min(.34,w.biosphere*.3))continue;const x=(gx+rr())*cell,z=(gz+rr())*cell,h=this.terrain(x,z),pr=this.project(x,z,h,horizon,focal);if(!pr||pr.dist>34||pr.dist<1.1)continue;items.push({...pr,r:rr(),biome:this.biomeAt(x,z,h)})}items.sort((a,b)=>b.dist-a.dist);for(const q of items){const s=q.scale,r=q.r,b=q.biome;if(['grassland','temperate_forest','rainforest','wetland','scrub','tundra'].includes(b)&&w.biosphere>.08){c.save();c.translate(q.x,q.y);c.strokeStyle=b==='tundra'?'rgba(154,175,128,.58)':'rgba(74,133,55,.72)';c.lineWidth=Math.max(.5,s*.012);for(let i=0;i<3+Math.floor(r*5);i++){const xx=(i-2)*s*.018,hh=s*(.08+r*.11)*(1+Math.sin(i*1.7)*.16),sway=Math.sin(t*.0014+i+r*7)*hh*.1*(.3+p.wind);c.beginPath();c.moveTo(xx,0);c.quadraticCurveTo(xx+sway,-hh*.55,xx+sway*.7,-hh);c.stroke()}c.restore()}else{c.fillStyle=`rgba(95,92,82,${.14+r*.22})`;const d=clamp(s*.03,1,5);c.beginPath();c.ellipse(q.x,q.y-d*.4,d,d*.5,0,0,PI*2);c.fill()}}}
 drawObjects(t,horizon,focal){
  const p=this.app.planet,pl=this.app.player,w=this.app.world;const cell=17,range=this.w<760?8:10,cx=Math.floor(pl.x/cell),cz=Math.floor(pl.z/cell),objs=[];for(let gx=cx-range;gx<=cx+range;gx++){for(let gz=cz-range;gz<=cz+range;gz++){const rr=seeded(p.seed,`obj2:${gx}:${gz}`);const x=(gx+rr())*cell,z=(gz+rr())*cell,h=this.terrain(x,z),biome=this.biomeAt(x,z,h);const richness=this.richnessForBiome(biome,w.biosphere);if(rr()>richness)continue;const pr=this.project(x,z,h,horizon,focal);if(!pr||pr.dist<2||pr.dist>190)continue;const speciesSeed=rr(),species=this.pickSpecies(biome,speciesSeed,w.biosphere);objs.push({...pr,xw:x,zw:z,h,r:rr(),species,biome,type:species.startsWith('creature:')?'creature':species==='rock'?'rock':'flora'})}}
  for(const o of w.outposts){const h=this.terrain(o.x,o.z),pr=this.project(o.x,o.z,h,horizon,focal);if(pr&&pr.dist<210)objs.push({...pr,xw:o.x,zw:o.z,h,r:.9,type:'outpost',species:'outpost',biome:'outpost'})}
  objs.sort((a,b)=>b.dist-a.dist);for(const o of objs){if(o.type==='flora')this.drawFloraSpecies(o.x,o.y,o.scale,o.r,o.species,o.biome,p,w,t);else if(o.type==='creature')this.drawCreatureSpecies(o.x,o.y,o.scale,o.r,o.species,p,t);else if(o.type==='outpost')this.drawOutpost(o.x,o.y,o.scale);else this.drawRock(o.x,o.y,o.scale,o.r,p,o.biome)}
 }
 richnessForBiome(b,bio){const R={rainforest:.92,temperate_forest:.84,conifer_forest:.78,wetland:.82,grassland:.64,scrub:.48,tundra:.28,desert:.22,alpine:.18,snowfield:.08,barren:.11,ice_barren:.04,shallow_water:.22,deep_ocean:.04};return clamp((R[b]||.16)*(.32+bio*.9))}
 pickSpecies(b,r,bio){
  const lists={rainforest:['tree:canopy','tree:palm','tree:baobab','plant:fern','plant:orchid','plant:vine','plant:mushroom','creature:glider','creature:grazer'],temperate_forest:['tree:oak','tree:maple','tree:birch','tree:beech','plant:fern','plant:shrub','plant:flower','plant:mushroom','creature:grazer','creature:bird'],conifer_forest:['tree:pine','tree:spruce','tree:cedar','plant:shrub','plant:fern','plant:mushroom','creature:grazer','creature:bird'],wetland:['plant:reed','plant:cattail','plant:fern','tree:willow','tree:mangrove','plant:lily','creature:bird','creature:grazer'],grassland:['plant:grass','plant:flower','plant:heather','plant:shrub','creature:grazer','creature:bird'],scrub:['plant:sage','plant:succulent','plant:grass','plant:heather','creature:grazer'],desert:['plant:saguaro','plant:agave','plant:succulent','rock','creature:grazer'],tundra:['plant:grass','plant:heather','plant:shrub','rock','creature:bird'],alpine:['rock','plant:heather','plant:flower'],snowfield:['rock','creature:bird'],barren:['rock','rock'],ice_barren:['rock'],shallow_water:['plant:reed','plant:cattail','plant:coral','plant:lily','rock'],deep_ocean:['rock'],cloud_deck:[]};const L=lists[b]||['rock'];let x=L[Math.floor(r*L.length)%L.length];if(bio<.08&&x!=='rock')x='rock';return x
 }
