 drawOrbit(t){const c=this.ctx,p=this.app.planet;c.fillStyle='#000';c.fillRect(0,0,this.w,this.h);this.drawStars(t,1);const cx=this.w*.52,cy=this.h*.49;const r=Math.min(this.w,this.h)*.22;const glow=c.createRadialGradient(cx-r*.2,cy-r*.25,r*.05,cx,cy,r*1.45);glow.addColorStop(0,`hsla(${p.hue} 90% 82% / .92)`);glow.addColorStop(.38,`hsla(${p.hue} ${Math.max(20,p.sat)}% ${Math.min(72,p.light+14)}% / 1)`);glow.addColorStop(.74,`hsla(${(p.hue+18)%360} ${p.sat}% ${Math.max(8,p.light-25)}% / 1)`);glow.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=glow;c.beginPath();c.arc(cx,cy,r*1.45,0,PI*2);c.fill();const sph=c.createRadialGradient(cx-r*.34,cy-r*.38,r*.05,cx,cy,r);sph.addColorStop(0,`hsl(${p.hue} ${Math.min(90,p.sat+22)}% ${Math.min(88,p.light+32)}%)`);sph.addColorStop(.55,`hsl(${p.hue} ${p.sat}% ${p.light}%)`);sph.addColorStop(1,`hsl(${(p.hue+12)%360} ${Math.max(15,p.sat-12)}% ${Math.max(5,p.light-32)}%)`);c.fillStyle=sph;c.beginPath();c.arc(cx,cy,r,0,PI*2);c.fill();this.drawPlanetWeatherShell(cx,cy,r,t);if(p.rings){c.save();c.strokeStyle='rgba(224,244,255,.38)';c.lineWidth=Math.max(4,r*.08);c.beginPath();c.ellipse(cx,cy,r*1.56,r*.42,-.18,0,PI*2);c.stroke();c.restore()}c.fillStyle='rgba(231,255,255,.9)';c.textAlign='center';c.font='800 14px ui-monospace,monospace';c.fillText(p.name.toUpperCase(),cx,cy+r+34);c.fillStyle='rgba(150,186,197,.75)';c.font='600 9px ui-monospace,monospace';c.fillText(`${fmt(p.gravityG,3)} g  •  ${fmt(p.escape,2)} km/s  •  ${fmt(p.tempC,0)} °C  •  ${p.known?'KNOWN ANCHOR':'PROCEDURAL WORLD'}`,cx,cy+r+51);this.drawFoldArc(t)}
 drawPlanetWeatherShell(cx,cy,r,t){const c=this.ctx,p=this.app.planet;if(p.atmo<.03)return;c.save();c.beginPath();c.arc(cx,cy,r*.99,0,PI*2);c.clip();c.globalAlpha=.13+Math.min(.2,p.atmo*.02);for(let i=0;i<7;i++){const yy=cy-r*.7+i*r*.22;const off=Math.sin(t*.00008*(1+i*.11)+i*2.2)*r*.16;c.strokeStyle='rgba(245,252,255,.7)';c.lineWidth=Math.max(1,r*.024);c.beginPath();c.ellipse(cx+off,yy,r*(.62-i*.018),r*.07,0,0,PI*2);c.stroke()}c.restore()}
 drawFoldArc(t){const c=this.ctx;const cx=this.w*.52,cy=this.h*.49,R=Math.min(this.w,this.h)*.31;c.save();c.strokeStyle='rgba(98,246,255,.13)';c.lineWidth=1;c.setLineDash([4,8]);c.beginPath();c.arc(cx,cy,R,-PI*.8,PI*.65);c.stroke();c.setLineDash([]);const a=(t*.00025)%(PI*2);const x=cx+Math.cos(a)*R,y=cy+Math.sin(a)*R;c.fillStyle='rgba(98,246,255,.85)';c.beginPath();c.arc(x,y,2.5,0,PI*2);c.fill();c.restore()}
 skyInfo(){const p=this.app.planet,s=this.app.sensors;let alt;if(p.name==='Earth'&&s.loc.ok)alt=solarAltitude(s.loc.lat,s.loc.lon,new Date(this.app.simDate));else alt=Math.sin(this.app.localDay*PI*2)*PI/2;const day=clamp((Math.sin(alt)+.12)/.35);return{alt,day}}
 drawSky(t){
  const c=this.ctx,p=this.app.planet,{alt,day}=this.skyInfo();this.app.lightFactor=day;const pressure=clamp(Math.log10(p.pressure+10)/5);const topHue=lerp(226,p.skyHue,day),botHue=lerp(246,(p.skyHue+16)%360,day);const g=c.createLinearGradient(0,0,0,this.h*.68);g.addColorStop(0,`hsl(${topHue} ${lerp(30,74,day)*pressure+12}% ${lerp(2,41,day)}%)`);g.addColorStop(.7,`hsl(${botHue} ${lerp(20,63,day)}% ${lerp(7,65,day)}%)`);g.addColorStop(1,`hsl(${(botHue+8)%360} 35% ${lerp(10,72,day)}%)`);c.fillStyle=g;c.fillRect(0,0,this.w,this.h);
  if(day<.72)this.drawStars(t,1-day*.92);const sunX=this.w*(.5+Math.sin(this.app.localDay*PI*2)*.42),sunY=this.h*(.42-Math.sin(alt)*.34);if(day>.02){const halo=c.createRadialGradient(sunX,sunY,2,sunX,sunY,135);halo.addColorStop(0,'rgba(255,255,247,.98)');halo.addColorStop(.055,'rgba(255,244,206,.88)');halo.addColorStop(.23,'rgba(255,205,120,.2)');halo.addColorStop(1,'rgba(255,180,80,0)');c.fillStyle=halo;c.beginPath();c.arc(sunX,sunY,135,0,PI*2);c.fill();c.fillStyle='rgba(255,252,232,.96)';c.beginPath();c.arc(sunX,sunY,clamp(7+this.w*.003,7,15),0,PI*2);c.fill();}
  this.drawHorizonHaze(day);if(p.name==='Earth'&&day<.45)this.drawMoon(t,day);
  if(this.app.world.storm>0){c.fillStyle=`rgba(20,27,37,${clamp(this.app.world.storm*.52)})`;c.fillRect(0,0,this.w,this.h);this.drawClouds(t,true)}else if(p.atmo>.05)this.drawClouds(t,false);
 }
